#!/bin/bash
# Infects with my vim plugins.

# first install pathogen
mkdir -p ~/.vim/autoload
cd ~/.vim/autoload
wget https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim

# now clone various plugins
mkdir -p ~/.vim/bundle
cd ~/.vim/bundle
git clone https://github.com/ervandew/supertab.git
git clone https://github.com/vim-airline/vim-airline.git
git clone https://github.com/altercation/vim-colors-solarized.git
git clone https://github.com/tpope/vim-fugitive.git
git clone https://github.com/airblade/vim-gitgutter.git
